# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'etudiantpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import webbrowser
import re
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets
from resultat import Ui_Form


class Ui_etdpage(object):

    def processString(self, newdata):

        specialChars = "()[]'"
        for specialChar in specialChars:
            newdata = newdata.replace(specialChar, '')

            newdata = newdata.replace(',', " ")
            newdata = newdata.replace('\\n', "\n\n")
            
        return newdata

    def Retourpage(self):
        self.retour.setVisible(False)
        self.result.setVisible(False)
        self.resultats.setVisible(False)
        self.recherche_2.setVisible(True)
        self.rechercheEns_2.setVisible(True)
        self.niveau_2.setVisible(True)





    def Recherche(self):
        if self.niveau_2.text():
            def regexp(expr, item):
                reg = re.compile(expr)
                return reg.search(item) is not None

            db = sqlite3.connect('SqlBdtest.db')
            db.create_function("REGEXP", 2, regexp)
            c = db.cursor()

            chaine = self.niveau_2.text()
            chaine.split()

            for mot in chaine.split():
                print(mot)
                c.execute(
                    '''SELECT Titre, Niveau, Description, identifiant FROM tbl_theme WHERE UPPER(Niveau) REGEXP UPPER(?) ''',
                    [mot])

            db.commit()
            data = c.fetchall()

            c.close()
            db.close()



        if self.rechercheEns_2.text():
            def regexp(expr, item):
                reg = re.compile(expr)
                return reg.search(item) is not None

            db = sqlite3.connect('SqlBdtest.db')
            db.create_function("REGEXP", 2, regexp)
            c = db.cursor()
            chaine = self.rechercheEns_2.text()

            chaine.split()

            for mot in chaine.split():
                print(mot)
                c.execute(
                    '''SELECT Titre,Niveau,Description,identifiant FROM tbl_theme WHERE UPPER(Titre) REGEXP UPPER(?) OR UPPER(Description) REGEXP UPPER(?) OR UPPER(identifiant) REGEXP UPPER(?)''',
                    [mot, mot, mot])

            db.commit()
            data = c.fetchall()

            c.close()
            db.close()



        if self.recherche_2.text():
            def regexp(expr, item):
                reg = re.compile(expr)
                return reg.search(item) is not None

            db = sqlite3.connect('SqlBdtest.db')
            db.create_function("REGEXP", 2, regexp)
            c = db.cursor()
            chaine = self.recherche_2.text()
            chaine.split()

            for mot in chaine.split():
                print(mot)
                c.execute(
                    '''SELECT Titre, Niveau, Description, identifiant FROM tbl_theme WHERE UPPER(Titre) REGEXP UPPER(?) OR UPPER(Description) REGEXP UPPER(?) ''',
                    [mot,mot])




            db.commit()
            data = c.fetchall()

            c.close()
            db.close()

        self.retour.setVisible(True)
        self.retour.clicked.connect(self.Retourpage)
        self.niveau_2.setVisible(False)
        self.recherche_2.setVisible(False)
        self.rechercheEns_2.setVisible(False)
        self.result.setVisible(True)
        self.resultats.setVisible(True)
        self.resultats.setText(self.processString(str(data)))








    def setupUi(self, etdpage):
        etdpage.setObjectName("etdpage")
        etdpage.resize(1440, 808)
        self.frame = QtWidgets.QFrame(etdpage)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1441, 901))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, -11, 1441, 151))
        self.frame_2.setStyleSheet("background : rgb(105, 148, 217);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(150, 40, 181, 101))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 30, 112, 112))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/Seal_of_Badji_Mokhtar_Annaba_University.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(750, 90, 641, 61))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plateforme_2 = QtWidgets.QPushButton(self.frame_5)
        self.plateforme_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.plateforme_2.setObjectName("plateforme_2")
        self.plateforme_2.clicked.connect(lambda: webbrowser.open('https://elearning.univ-annaba.dz'))
        self.horizontalLayout.addWidget(self.plateforme_2)
        self.listeEnseignants_2 = QtWidgets.QPushButton(self.frame_5)
        self.listeEnseignants_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.listeEnseignants_2.setObjectName("listeEnseignants_2")
        self.listeEnseignants_2.clicked.connect(lambda: webbrowser.open('https://perso.univ-annaba.dz/fr/liste-des-enseignants.php?Departement=Informatique&Nb=11'))
        self.horizontalLayout.addWidget(self.listeEnseignants_2)
        self.documentation_2 = QtWidgets.QPushButton(self.frame_5)
        self.documentation_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.documentation_2.setObjectName("documentation_2")
        self.documentation_2.clicked.connect(lambda: webbrowser.open('https://biblio.univ-annaba.dz'))
        self.horizontalLayout.addWidget(self.documentation_2)
        self.departement_2 = QtWidgets.QPushButton(self.frame_5)
        self.departement_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.departement_2.setObjectName("departement_2")
        self.departement_2.clicked.connect(lambda: webbrowser.open('https://perso.univ-annaba.dz/fr/liste-des-departements.php'))
        self.horizontalLayout.addWidget(self.departement_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 140, 1451, 611))
        self.frame_3.setStyleSheet("background : rgb(255, 255, 255);\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.widget_2 = QtWidgets.QWidget(self.frame_3)
        self.widget_2.setGeometry(QtCore.QRect(70, 30, 1311, 551))
        self.widget_2.setStyleSheet("background : rgb(38, 72, 122);\n"
"border -radius: 40px;\n"
"border style: outset;\n"
"border-radius: 20px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.widget_2.setObjectName("widget_2")

        self.result = QtWidgets.QWidget(self.frame_3)
        self.result.setGeometry(QtCore.QRect(70, 30, 1311, 551))
        self.result.setStyleSheet("background : rgb(38, 72, 122);\n"
"border -radius: 40px;\n"
"border style: outset;\n"
"border-radius: 20px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.result.setObjectName("result")
        self.result.setVisible(False)

        self.resultats = QtWidgets.QTextEdit(self.frame_3)
        self.resultats.setGeometry(QtCore.QRect(70, 30, 1311, 551))
        self.resultats.setStyleSheet("background : rgb(255, 255, 255);\n"
                                     "font: 15pt \"MS Shell Dlg 2\";\n"
                                     "border-style : outset;\n"
                                     "border-radius: 10px;\n"
                                     "border-color: black;\n"
                                     "padding: 6px;\n"
                                     "color:#000000;\n"
                                     "min-width: 10px;")


        self.resultats.setObjectName("resultat")
        self.resultats.setEnabled(False)
        self.resultats.setVisible(False)

        self.retour = QtWidgets.QPushButton(self.frame_3)
        self.retour.setGeometry(QtCore.QRect(1050, 490, 231, 41))
        self.retour.setStyleSheet("background : rgb(38, 72, 122);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: white;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.retour.setText("Retour")


        self.retour.setObjectName("Retour")
        self.retour.setVisible(False)







        self.recherche_2 = QtWidgets.QLineEdit(self.widget_2)
        self.recherche_2.setGeometry(QtCore.QRect(30, 150, 821, 41))
        self.recherche_2.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.recherche_2.setObjectName("recherche_2")
        self.recherche_2.setPlaceholderText("Mot clé du thème")
        self.recherche_2.setMaxLength(100)
        self.label_20 = QtWidgets.QLabel(self.widget_2)
        self.label_20.setGeometry(QtCore.QRect(0, 10, 1311, 61))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_2)
        self.label_21.setGeometry(QtCore.QRect(30, 100, 421, 41))
        self.label_21.setObjectName("label_21")
        self.rechercheEns_2 = QtWidgets.QLineEdit(self.widget_2)
        self.rechercheEns_2.setGeometry(QtCore.QRect(30, 250, 821, 41))
        self.rechercheEns_2.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.rechercheEns_2.setObjectName("rechercheEns_2")
        self.rechercheEns_2.setMaxLength(25)
        self.rechercheEns_2.setPlaceholderText("Exemple: prenom.nom")
        self.label_23 = QtWidgets.QLabel(self.widget_2)
        self.label_23.setGeometry(QtCore.QRect(30, 310, 141, 41))
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.widget_2)
        self.label_25.setGeometry(QtCore.QRect(30, 200, 341, 41))
        self.label_25.setObjectName("label_25")
        self.niveau_2 = QtWidgets.QLineEdit(self.widget_2)
        self.niveau_2.setGeometry(QtCore.QRect(30, 360, 361, 41))
        self.niveau_2.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.niveau_2.setObjectName("niveau_2")
        self.niveau_2.setPlaceholderText("Exemple : L3,M1,M2")
        self.niveau_2.setMaxLength(20)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(1030, 480, 231, 41))
        self.pushButton.setStyleSheet("background : rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Recherche)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(-70, 750, 1511, 151))
        self.frame_4.setStyleSheet("background : rgb(105, 148, 217);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(80, 20, 89, 89))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Downloads/Seal_of_Badji_Mokhtar_Annaba_University.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(180, 30, 171, 81))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(650, 10, 58, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(1220, 10, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(880, 10, 111, 16))
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.frame_4)
        self.line.setGeometry(QtCore.QRect(770, 10, 16, 111))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame_4)
        self.line_2.setGeometry(QtCore.QRect(1080, 10, 16, 111))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(600, 80, 58, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(600, 50, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(790, 30, 261, 41))
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(790, 70, 221, 16))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(790, 90, 221, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(1210, 40, 41, 41))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../../../Downloads/174857.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(1100, 40, 51, 41))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../../../Downloads/ee7c3b568d2f8f599757a55805464256.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(1260, 40, 45, 43))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../../../Downloads/youtube_PNG1.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(1160, 40, 41, 41))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../../../Downloads/Generic_Feed-icon.svg.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(1310, 36, 48, 48))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("../../../Downloads/580b57fcd9996e24bc43c521.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(1360, 40, 46, 44))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("../../../Downloads/Twitter-icon.png.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")

        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(600, 50, 81, 16))
        self.label_9.setText("")
        self.label_9.setObjectName("Plateforme")
        self.label_9.setText('<a href="https://elearning.univ-annaba.dz">Plateforme</a>')
        self.label_9.setOpenExternalLinks(True)

        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(600, 80, 58, 21))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_8.setText('<a href="https://goo.gl/maps/epRHUwKk6FJ5LGgKA">Maps</a>')
        self.label_8.setOpenExternalLinks(True)

        self.facebook = QtWidgets.QLabel(self.frame_4)
        self.facebook.setGeometry(QtCore.QRect(1100, 80, 56, 41))
        self.facebook.setText("")
        self.facebook.setObjectName("Facebook")
        self.facebook.setText('<a href="https://www.facebook.com/UbmaOfficial/">Facebook</a>')
        self.facebook.setOpenExternalLinks(True)

        self.rss = QtWidgets.QLabel(self.frame_4)
        self.rss.setGeometry(QtCore.QRect(1160, 80, 51, 41))
        self.rss.setText("")
        self.rss.setObjectName("   RSS")
        self.rss.setText('<a href="https://www.univ-annaba.dz/?format=feed&type=rss">RSS</a>')
        self.rss.setOpenExternalLinks(True)

        self.linkedin = QtWidgets.QLabel(self.frame_4)
        self.linkedin.setGeometry(QtCore.QRect(1210, 80, 56, 41))
        self.linkedin.setText("")
        self.linkedin.setObjectName("Linkedin")
        self.linkedin.setText('<a href="https://www.linkedin.com/school/ubma/mycompany/">Linkedin</a>')
        self.linkedin.setOpenExternalLinks(True)

        self.youtube = QtWidgets.QLabel(self.frame_4)
        self.youtube.setGeometry(QtCore.QRect(1260, 80, 56, 41))
        self.youtube.setText("")
        self.youtube.setObjectName("Youtube")
        self.youtube.setText('<a href="https://www.youtube.com/c/BadjiMokhtarAnnabaUniversity/">Youtube</a>')
        self.youtube.setOpenExternalLinks(True)

        self.instagram = QtWidgets.QLabel(self.frame_4)
        self.instagram.setGeometry(QtCore.QRect(1310, 80, 56, 41))
        self.instagram.setText("")
        self.instagram.setObjectName("Instagm")
        self.instagram.setText('<a href="https://www.instagram.com/ubma.official/">Instagm</a>')
        self.instagram.setOpenExternalLinks(True)

        self.twitter = QtWidgets.QLabel(self.frame_4)
        self.twitter.setGeometry(QtCore.QRect(1360, 80, 56, 41))
        self.twitter.setText("")
        self.twitter.setObjectName("Twitter")
        self.twitter.setText('<a href="https://twitter.com/UbmaOfficial?s=20 ">Twitter</a>')
        self.twitter.setOpenExternalLinks(True)

        self.retranslateUi(etdpage)
        QtCore.QMetaObject.connectSlotsByName(etdpage)

    def retranslateUi(self, etdpage):
        _translate = QtCore.QCoreApplication.translate
        etdpage.setWindowTitle(_translate("etdpage", "Form"))
        self.label_3.setText(_translate("etdpage", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Université </span><span style=\" font-size:24pt;\"><br/></span><span style=\" font-size:24pt; font-weight:600;\">Badji Mokhtar</span><span style=\" font-size:24pt;\"><br/></span><span style=\" font-size:24pt; font-weight:600;\">-Annaba-</span></p></body></html>"))
        self.plateforme_2.setText(_translate("etdpage", "Plateforme"))
        self.listeEnseignants_2.setText(_translate("etdpage", "Liste Enseignants"))
        self.documentation_2.setText(_translate("etdpage", "Documentation"))
        self.departement_2.setText(_translate("etdpage", "Département"))
        self.label_20.setText(_translate("etdpage", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#d5d5d5;\">Rechercher un Thème / Enseignant :</span></p><p align=\"center\"><span style=\" font-size:36pt;\"><br/></span></p><p align=\"center\"><span style=\" font-size:36pt;\"><br/></span></p></body></html>"))
        self.label_21.setText(_translate("etdpage", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#d5d5d5;\">Rechercher un thème par mot clé :</span><span style=\" font-size:24pt;\"><br/></span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.label_23.setText(_translate("etdpage", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#d5d5d5;\">Niveau :</span><span style=\" font-size:24pt;\"><br/></span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.label_25.setText(_translate("etdpage", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#d5d5d5;\">Rechercher un enseignant :</span><span style=\" font-size:24pt;\"><br/></span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.pushButton.setText(_translate("etdpage", "Rechercher"))
        self.label_4.setText(_translate("etdpage", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Université </span><span style=\" font-size:18pt;\"><br/></span><span style=\" font-size:18pt; font-weight:600;\">Badji Mokhtar</span><span style=\" font-size:18pt;\"><br/></span><span style=\" font-size:18pt; font-weight:600;\">-Annaba-</span></p></body></html>"))
        self.label_5.setText(_translate("etdpage", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Liens</span></p></body></html>"))
        self.label_6.setText(_translate("etdpage", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Nous suivre</span></p></body></html>"))
        self.label_7.setText(_translate("etdpage", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Nous contacter</span></p></body></html>"))
        self.label_11.setText(_translate("etdpage", "<html><head/><body><p><span style=\" font-size:14pt;\">Adresse : Université Badji Mokhtar</span><br/><span style=\" font-size:14pt;\">-Annaba, B.P.12, Annaba 23000 Algérie</span></p></body></html>"))
        self.label_10.setText(_translate("etdpage", "<html><head/><body><p><span style=\" font-size:14pt;\">Téléphone : +213 (0) 38 57 02 05</span></p></body></html>"))
        self.label_12.setText(_translate("etdpage", "<html><head/><body><p><span style=\" font-size:14pt;\">E-mail : elearning@univ-annaba.dz</span></p></body></html>"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    etdpage = QtWidgets.QWidget()
    ui = Ui_etdpage()
    ui.setupUi(etdpage)
    etdpage.show()
    sys.exit(app.exec_())
