# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pageacceuil.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import webbrowser
import sqlite3
import sys


from PyQt5 import QtCore, QtGui, QtWidgets
from etudiantpage import Ui_etdpage
from enseignantpage import Ui_enspage







class Ui_pacceuil(object):



    def etudiantpage(self):
        self.etdpage = QtWidgets.QWidget()
        self.ui = Ui_etdpage()
        self.ui.setupUi(self.etdpage)
        self.etdpage.show()


    def enseignantpage(self):
        self.enspage = QtWidgets.QWidget()
        self.ui = Ui_enspage()
        self.ui.setupUi(self.enspage)
        self.enspage.show()


    def loginEtd(self):

        if (self.idEtd_1.text() and self.mdpEtd_1):
            identifiant = self.idEtd_1.text()
            mdp = self.mdpEtd_1.text()

            with sqlite3.connect("SqlBdtest.db") as db:
                cursor = db.cursor()

            find_user = ("SELECT * FROM tbl_login WHERE identifiant = ? AND mdp = ?")
            cursor.execute(find_user, [(identifiant), (mdp)])
            results = cursor.fetchall()
            if results:
                while True:
                    self.etdpage = QtWidgets.QWidget()
                    self.ui = Ui_etdpage()
                    self.ui.setupUi(self.etdpage)
                    self.etdpage.show()
                    break


    def loginEns(self):
        identifiant = self.idEns_1.text()
        mdp = self.mdpEns_1.text()

        with sqlite3.connect("SqlBdtest.db") as db:
            cursor = db.cursor()

        find_user = ("SELECT * FROM tbl_login1 WHERE identifiant = ? AND mdp = ?")
        cursor.execute(find_user, [(identifiant), (mdp)])
        results = cursor.fetchall()
        if results:
            while True:
                self.frame_3.setVisible(True)
                self.frame_8.setVisible(False)
                break


    def messagebox(self,title,message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()



    def loadData(self):
        identifiant = self.idEns_1.text()
        db = sqlite3.connect('SqlBdtest.db')
        c = db.cursor()


        query = "SELECT * FROM tbl_theme"
        result = db.execute(query)
        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for columnn_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, columnn_number, QtWidgets.QTableWidgetItem(str(data)))

        db.close()




    def add_to_db(self):
        try:
            a = self.ntheme.text()
            b = self.recherche_3.text()
            c = self.niveau_3.text()
            d = self.description_3.toPlainText()
            e = self.idEns_1.text()
            n1 = 'L3'
            n2 = 'M1'
            n3 = 'M2'
            n4 = 'l3'
            n5 = 'm1'
            n6 = 'm2'

            con = sqlite3.connect("SqlBdtest.db")
            cursor = con.cursor()

            cursor.execute("CREATE TABLE IF NOT EXISTS tbl_theme(Num_theme INTEGER, Titre VARCHAR, Niveau VARCHAR, Description VARCHAR, identifiant VARCHAR)")
            con.commit()
            if((c == n1) or (c == n2) or (c == n3) or (c == n4) or (c == n5) or (c == n6)):
                cursor.execute("Insert into tbl_theme Values(?,?,?,?,?)",(a,b,c,d,e))
                con.commit()
                self.messagebox("Bravo", "Thème ajouté avec succès")
                self.ntheme.setText("")
                self.recherche_3.setText("")
                self.niveau_3.setText("")
                self.description_3.setText("")
                self.loadData()
        except:
            pass




    def Delete_Data(self):

        con = sqlite3.connect("SqlBdtest.db")
        cursor = con.cursor()

        idens = self.idEns_1.text()
        content = 'SELECT * FROM tbl_theme'

        res = cursor.execute(content)
        for row in enumerate(res):
            if row[0] == self.tableWidget.currentRow():

                data = row[1]
                ntheme = data[0]
                title = data[1]
                niveau = data[2]
                descripp = data [3]
                identifiant = data[4]
                if (idens == data[4]):
                    cursor.execute("DELETE FROM tbl_theme WHERE Num_theme = ? AND Titre = ? AND Niveau = ? AND Description = ? AND identifiant = ?",(ntheme, title, niveau, descripp, identifiant))
                    con.commit()

                    self.loadData()




    def afficher_mthemes(self):

        identifiant = self.idEns_1.text()
        db = sqlite3.connect('SqlBdtest.db')
        c = db.cursor()

        query = "SELECT * FROM tbl_theme WHERE identifiant=?"
        c.fetchall()
        result = db.execute(query,[(identifiant)])

        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for columnn_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, columnn_number, QtWidgets.QTableWidgetItem(str(data)))

        db.close()





    def setupUi(self, pacceuil):
        pacceuil.setObjectName("pacceuil")
        pacceuil.resize(1440, 808)
        self.frame = QtWidgets.QFrame(pacceuil)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1441, 891))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(0, -11, 1441, 151))
        self.frame_6.setStyleSheet("background : rgb(105, 148, 217);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_25 = QtWidgets.QLabel(self.frame_6)
        self.label_25.setGeometry(QtCore.QRect(150, 40, 181, 101))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_6)
        self.label_26.setGeometry(QtCore.QRect(20, 30, 112, 112))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("../../../Downloads/Seal_of_Badji_Mokhtar_Annaba_University.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(750, 90, 641, 61))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plateforme_1 = QtWidgets.QPushButton(self.frame_7)
        self.plateforme_1.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.plateforme_1.setObjectName("plateforme_1")
        self.plateforme_1.clicked.connect(lambda: webbrowser.open('https://elearning.univ-annaba.dz'))
        self.horizontalLayout_2.addWidget(self.plateforme_1)
        self.listeEnseignants_1 = QtWidgets.QPushButton(self.frame_7)
        self.listeEnseignants_1.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.listeEnseignants_1.setObjectName("listeEnseignants_1")
        self.listeEnseignants_1.clicked.connect(lambda: webbrowser.open('https://perso.univ-annaba.dz/fr/liste-des-enseignants.php?Departement=Informatique&Nb=11'))
        self.horizontalLayout_2.addWidget(self.listeEnseignants_1)
        self.documentation_1 = QtWidgets.QPushButton(self.frame_7)
        self.documentation_1.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.documentation_1.setObjectName("documentation_1")
        self.documentation_1.clicked.connect(lambda: webbrowser.open('https://biblio.univ-annaba.dz'))
        self.horizontalLayout_2.addWidget(self.documentation_1)
        self.departement_1 = QtWidgets.QPushButton(self.frame_7)
        self.departement_1.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.departement_1.setObjectName("departement_1")
        self.departement_1.clicked.connect(lambda: webbrowser.open('https://facsci.univ-annaba.dz/2013/07/22/departement-dinformatique/'))
        self.horizontalLayout_2.addWidget(self.departement_1)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(0, 140, 1451, 601))
        self.frame_8.setStyleSheet("background : rgb(255, 255, 255);\n""")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.enseignant_2 = QtWidgets.QWidget(self.frame_8)
        self.enseignant_2.setGeometry(QtCore.QRect(800, 30, 551, 551))
        self.enseignant_2.setStyleSheet("background : rgb(38, 72, 122);\n"
"border -radius: 40px;\n"
"border style: outset;\n"
"border-radius: 20px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.enseignant_2.setObjectName("enseignant_2")
        self.mdpEns_1 = QtWidgets.QLineEdit(self.enseignant_2)
        self.mdpEns_1.setGeometry(QtCore.QRect(230, 280, 271, 41))
        self.mdpEns_1.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.mdpEns_1.setObjectName("mdpEns_1")
        self.mdpEns_1.setMaxLength(20)
        self.mdpEns_1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mdpEns_1.setPlaceholderText("Ubma.JJMMAAAA")
        self.idEns_1 = QtWidgets.QLineEdit(self.enseignant_2)
        self.idEns_1.setGeometry(QtCore.QRect(230, 170, 271, 41))
        self.idEns_1.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.idEns_1.setObjectName("idEns_1")
        self.idEns_1.setMaxLength(20)
        self.idEns_1.setPlaceholderText("prenom.nom")
        self.pushButton_11 = QtWidgets.QPushButton(self.enseignant_2)
        self.pushButton_11.setGeometry(QtCore.QRect(380, 470, 141, 41))
        self.pushButton_11.clicked.connect(self.loginEns)
        self.pushButton_11.setStyleSheet("background : rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_27 = QtWidgets.QLabel(self.enseignant_2)
        self.label_27.setGeometry(QtCore.QRect(0, 20, 551, 61))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.enseignant_2)
        self.label_28.setGeometry(QtCore.QRect(10, 170, 211, 41))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.enseignant_2)
        self.label_29.setGeometry(QtCore.QRect(40, 280, 181, 41))
        self.label_29.setObjectName("label_29")
        self.etudiant_2 = QtWidgets.QWidget(self.frame_8)
        self.etudiant_2.setGeometry(QtCore.QRect(110, 30, 551, 551))
        self.etudiant_2.setStyleSheet("background : rgb(38, 72, 122);\n"
"border -radius: 40px;\n"
"border style: outset;\n"
"border-radius: 20px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.etudiant_2.setObjectName("etudiant_2")
        self.mdpEtd_1 = QtWidgets.QLineEdit(self.etudiant_2)
        self.mdpEtd_1.setGeometry(QtCore.QRect(220, 280, 271, 41))
        self.mdpEtd_1.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.mdpEtd_1.setObjectName("mdpEtd_1")
        self.mdpEtd_1.setMaxLength(20)
        self.mdpEtd_1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mdpEtd_1.setPlaceholderText("Ubma.numéro d'inscription")
        self.idEtd_1 = QtWidgets.QLineEdit(self.etudiant_2)
        self.idEtd_1.setGeometry(QtCore.QRect(220, 170, 271, 41))
        self.idEtd_1.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.idEtd_1.setObjectName("idEtd_1")
        self.idEtd_1.setMaxLength(20)
        self.idEtd_1.setPlaceholderText("prenom.nom")
        self.pushButton_12 = QtWidgets.QPushButton(self.etudiant_2)
        self.pushButton_12.setGeometry(QtCore.QRect(370, 470, 141, 41))
        self.pushButton_12.clicked.connect(self.loginEtd)
        self.pushButton_12.setStyleSheet("background : rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-style : outset;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.pushButton_12.setObjectName("pushButton_12")

        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 140, 1451, 611))
        self.frame_3.setStyleSheet("background : rgb(255, 255, 255);\n"
                                   "")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.setVisible(False)
        self.enseignant = QtWidgets.QWidget(self.frame_3)
        self.enseignant.setGeometry(QtCore.QRect(800, 30, 551, 551))
        self.enseignant.setStyleSheet("background : rgb(38, 72, 122);\n"
                                      "border -radius: 40px;\n"
                                      "border style: outset;\n"
                                      "border-radius: 20px;\n"
                                      "border-color: black;\n"
                                      "padding: 6px;\n"
                                      "min-width: 10px;")
        self.enseignant.setObjectName("enseignant")
        self.label_19 = QtWidgets.QLabel(self.enseignant)
        self.label_19.setGeometry(QtCore.QRect(0, 20, 551, 61))
        self.label_19.setObjectName("label_19")
        self.tableWidget = QtWidgets.QTableWidget(self.enseignant)
        self.tableWidget.setGeometry(QtCore.QRect(30, 90, 491, 441))
        self.tableWidget.setStyleSheet("background:rgb(255, 255, 255);\n"
                                       "border-style:outset;\n"
                                       "border-color:black;\n"
                                       "border-radius:10px;\n"
                                       "padding:0px;\n"
                                       "")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget.setRowCount(14)
        self.tableWidget.setColumnCount(5)

        self.etudiant = QtWidgets.QWidget(self.frame_3)
        self.etudiant.setGeometry(QtCore.QRect(110, 30, 551, 551))
        self.etudiant.setStyleSheet("background : rgb(38, 72, 122);\n"
                                    "border -radius: 40px;\n"
                                    "border style: outset;\n"
                                    "border-radius: 20px;\n"
                                    "border-color: black;\n"
                                    "padding: 6px;\n"
                                    "min-width: 10px;")
        self.etudiant.setObjectName("etudiant")
        self.recherche_3 = QtWidgets.QLineEdit(self.etudiant)
        self.recherche_3.setGeometry(QtCore.QRect(30, 130, 491, 41))
        self.recherche_3.setStyleSheet("background:rgb(255, 255, 255);\n"
                                       "border-style : outset;\n"
                                       "border-radius: 10px;\n"
                                       "border-color: black;\n"
                                       "padding: 6px;\n"
                                       "min-width: 10px;")
        self.recherche_3.setObjectName("recherche_3")
        self.recherche_3.setPlaceholderText("Titre du thème")
        self.recherche_3.setMaxLength(70)

        self.label_20 = QtWidgets.QLabel(self.etudiant)
        self.label_20.setGeometry(QtCore.QRect(0, 20, 551, 51))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.etudiant)
        self.label_21.setGeometry(QtCore.QRect(30, 80, 141, 41))
        self.label_21.setObjectName("label_21")
        self.niveau_3 = QtWidgets.QLineEdit(self.etudiant)
        self.niveau_3.setGeometry(QtCore.QRect(30, 230, 231, 41))
        self.niveau_3.setStyleSheet("background:rgb(255, 255, 255);\n"
                                    "border-style : outset;\n"
                                    "border-radius: 10px;\n"
                                    "border-color: black;\n"
                                    "padding: 6px;\n"
                                    "min-width: 10px;")
        self.niveau_3.setObjectName("niveau_3")
        self.niveau_3.setPlaceholderText("L3, M1, M2")
        self.niveau_3.setMaxLength(20)
        self.label_23 = QtWidgets.QLabel(self.etudiant)
        self.label_23.setGeometry(QtCore.QRect(30, 180, 141, 41))
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.etudiant)
        self.label_25.setGeometry(QtCore.QRect(30, 280, 191, 41))
        self.label_25.setObjectName("label_25")
        self.description_3 = QtWidgets.QTextEdit(self.etudiant)
        self.description_3.setGeometry(QtCore.QRect(30, 320, 491, 171))
        self.description_3.setStyleSheet("background:rgb(255, 255, 255);\n"
                                         "border-style : outset;\n"
                                         "border-radius: 10px;\n"
                                         "border-color: black;\n"
                                         "padding: 6px;\n"
                                         "min-width: 10px;")
        self.description_3.setObjectName("description_3")
        self.ajouter = QtWidgets.QPushButton(self.etudiant)
        self.ajouter.setGeometry(QtCore.QRect(410, 500, 112, 32))
        self.ajouter.setStyleSheet("background : rgb(255, 255, 255);\n"
                                   "font: 20pt \"MS Shell Dlg 2\";\n"
                                   "border-style : outset;\n"
                                   "border-radius: 10px;\n"
                                   "border-color: black;\n"
                                   "padding: 6px;\n"
                                   "min-width: 10px;")
        self.ajouter.setObjectName("ajouter")
        self.ajouter.clicked.connect(self.add_to_db)



        self.supprimmer = QtWidgets.QPushButton(self.etudiant)
        self.supprimmer.setGeometry(QtCore.QRect(170, 500, 112, 32))
        self.supprimmer.setStyleSheet("background : rgb(255, 255, 255);\n"
                                      "font: 20pt \"MS Shell Dlg 2\";\n"
                                      "border-style : outset;\n"
                                      "border-radius: 10px;\n"
                                      "border-color: black;\n"
                                      "padding: 6px;\n"
                                      "min-width: 10px;")
        self.supprimmer.setObjectName("supprimmer")
        self.supprimmer.setText("Effacer")
        self.supprimmer.clicked.connect(self.Delete_Data)

        self.mesthemes = QtWidgets.QPushButton(self.etudiant)
        self.mesthemes.setGeometry(QtCore.QRect(50, 500, 112, 32))
        self.mesthemes.setStyleSheet("background : rgb(255, 255, 255);\n"
                                      "font: 20pt \"MS Shell Dlg 2\";\n"
                                      "border-style : outset;\n"
                                      "border-radius: 10px;\n"
                                      "border-color: black;\n"
                                      "padding: 6px;\n"
                                      "min-width: 10px;")
        self.mesthemes.setObjectName("mesthemes")
        self.mesthemes.setText("Thèmes")
        self.mesthemes.clicked.connect(self.afficher_mthemes)

        self.label_26 = QtWidgets.QLabel(self.etudiant)
        self.label_26.setGeometry(QtCore.QRect(290, 180, 181, 41))
        self.label_26.setObjectName("label_26")

        self.ntheme = QtWidgets.QLineEdit(self.etudiant)
        self.ntheme.setGeometry(QtCore.QRect(280, 230, 241, 41))
        self.ntheme.setStyleSheet("background:rgb(255, 255, 255);\n"
                                  "border-style : outset;\n"
                                  "border-radius: 10px;\n"
                                  "border-color: black;\n"
                                  "padding: 6px;\n"
                                  "min-width: 10px;")
        self.ntheme.setObjectName("ntheme")
        self.ntheme.setPlaceholderText("Dernier N° Thème")


        self.afficher = QtWidgets.QPushButton(self.etudiant)
        self.afficher.setGeometry(QtCore.QRect(290, 500, 112, 32))
        self.afficher.setStyleSheet("background : rgb(255, 255, 255);\n"
                                    "font: 20pt \"MS Shell Dlg 2\";\n"
                                    "border-style : outset;\n"
                                    "border-radius: 10px;\n"
                                    "border-color: black;\n"
                                    "padding: 6px;\n"
                                    "min-width: 10px;")
        self.afficher.setObjectName("a")
        self.afficher.setText("Afficher")
        self.afficher.clicked.connect(self.loadData)

        self.label_30 = QtWidgets.QLabel(self.etudiant_2)
        self.label_30.setGeometry(QtCore.QRect(0, 20, 551, 51))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.etudiant_2)
        self.label_31.setGeometry(QtCore.QRect(20, 170, 171, 41))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.etudiant_2)
        self.label_32.setGeometry(QtCore.QRect(30, 280, 181, 41))
        self.label_32.setObjectName("label_32")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(-70, 740, 1511, 151))
        self.frame_9.setStyleSheet("background : rgb(105, 148, 217);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_33 = QtWidgets.QLabel(self.frame_9)
        self.label_33.setGeometry(QtCore.QRect(80, 20, 89, 89))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("../../../Downloads/Seal_of_Badji_Mokhtar_Annaba_University.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_9)
        self.label_34.setGeometry(QtCore.QRect(180, 30, 171, 81))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame_9)
        self.label_35.setGeometry(QtCore.QRect(650, 10, 58, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame_9)
        self.label_36.setGeometry(QtCore.QRect(1220, 10, 91, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame_9)
        self.label_37.setGeometry(QtCore.QRect(880, 10, 111, 16))
        self.label_37.setObjectName("label_37")
        self.line_3 = QtWidgets.QFrame(self.frame_9)
        self.line_3.setGeometry(QtCore.QRect(770, 10, 16, 111))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame_9)
        self.line_4.setGeometry(QtCore.QRect(1080, 10, 16, 111))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_38 = QtWidgets.QLabel(self.frame_9)
        self.site = QtWidgets.QLabel(self.frame_9)
        self.site.setGeometry(QtCore.QRect(600, 50, 81, 16))
        self.site.setText("")
        self.site.setObjectName("Plateforme")
        self.site.setText('<a href="https://elearning.univ-annaba.dz">Plateforme</a>')
        self.site.setOpenExternalLinks(True)

        self.maps = QtWidgets.QLabel(self.frame_9)
        self.maps.setGeometry(QtCore.QRect(600, 80, 58, 21))
        self.maps.setText("")
        self.maps.setObjectName("Maps")
        self.maps.setText('<a href="https://goo.gl/maps/epRHUwKk6FJ5LGgKA">Maps</a>')
        self.maps.setOpenExternalLinks(True)



        self.label_40 = QtWidgets.QLabel(self.frame_9)
        self.label_40.setGeometry(QtCore.QRect(790, 30, 261, 41))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_9)
        self.label_41.setGeometry(QtCore.QRect(790, 70, 221, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame_9)
        self.label_42.setGeometry(QtCore.QRect(790, 90, 221, 16))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_9)
        self.label_43.setGeometry(QtCore.QRect(1210, 40, 41, 41))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("../../../Downloads/174857.png"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")

        self.linkedin = QtWidgets.QLabel(self.frame_9)
        self.linkedin.setGeometry(QtCore.QRect(1210, 80, 56, 41))
        self.linkedin.setText("")
        self.linkedin.setObjectName("Linkedin")
        self.linkedin.setText('<a href="https://www.linkedin.com/school/ubma/mycompany/">Linkedin</a>')
        self.linkedin.setOpenExternalLinks(True)

        self.label_44 = QtWidgets.QLabel(self.frame_9)
        self.label_44.setGeometry(QtCore.QRect(1100, 40, 51, 41))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("../../../Downloads/ee7c3b568d2f8f599757a55805464256.png"))
        self.label_44.setScaledContents(True)
        self.label_44.setObjectName("label_44")

        self.facebook = QtWidgets.QLabel(self.frame_9)
        self.facebook.setGeometry(QtCore.QRect(1100, 80, 56, 41))
        self.facebook.setText("")
        self.facebook.setObjectName("Facebook")
        self.facebook.setText('<a href="https://www.facebook.com/UbmaOfficial/">Facebook</a>')
        self.facebook.setOpenExternalLinks(True)

        self.label_45 = QtWidgets.QLabel(self.frame_9)
        self.label_45.setGeometry(QtCore.QRect(1260, 40, 45, 43))
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap("../../../Downloads/youtube_PNG1.png"))
        self.label_45.setScaledContents(True)
        self.label_45.setObjectName("label_45")

        self.youtube = QtWidgets.QLabel(self.frame_9)
        self.youtube.setGeometry(QtCore.QRect(1260, 80, 56, 41))
        self.youtube.setText("")
        self.youtube.setObjectName("Youtube")
        self.youtube.setText('<a href="https://www.youtube.com/c/BadjiMokhtarAnnabaUniversity/">Youtube</a>')
        self.youtube.setOpenExternalLinks(True)

        self.label_46 = QtWidgets.QLabel(self.frame_9)
        self.label_46.setGeometry(QtCore.QRect(1160, 40, 41, 41))
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap("../../../Downloads/Generic_Feed-icon.svg.png"))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName("label_46")

        self.rss = QtWidgets.QLabel(self.frame_9)
        self.rss.setGeometry(QtCore.QRect(1160, 80, 51, 41))
        self.rss.setText("")
        self.rss.setObjectName("   RSS")
        self.rss.setText('<a href="https://www.univ-annaba.dz/?format=feed&type=rss">RSS</a>')
        self.rss.setOpenExternalLinks(True)




        self.label_47 = QtWidgets.QLabel(self.frame_9)
        self.label_47.setGeometry(QtCore.QRect(1310, 36, 48, 48))
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap("../../../Downloads/580b57fcd9996e24bc43c521.png"))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName("label_47")

        self.instagram = QtWidgets.QLabel(self.frame_9)
        self.instagram.setGeometry(QtCore.QRect(1310, 80, 56, 41))
        self.instagram.setText("")
        self.instagram.setObjectName("Instagm")
        self.instagram.setText('<a href="https://www.instagram.com/ubma.official/">Instagm</a>')
        self.instagram.setOpenExternalLinks(True)

        self.label_48 = QtWidgets.QLabel(self.frame_9)
        self.label_48.setGeometry(QtCore.QRect(1360, 40, 46, 44))
        self.label_48.setText("")
        self.label_48.setPixmap(QtGui.QPixmap("../../../Downloads/Twitter-icon.png.png"))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName("label_48")

        self.twitter = QtWidgets.QLabel(self.frame_9)
        self.twitter.setGeometry(QtCore.QRect(1360, 80, 56, 41))
        self.twitter.setText("")
        self.twitter.setObjectName("Twitter")
        self.twitter.setText('<a href="https://twitter.com/UbmaOfficial?s=20 ">Twitter</a>')
        self.twitter.setOpenExternalLinks(True)

        self.retranslateUi(pacceuil)
        QtCore.QMetaObject.connectSlotsByName(pacceuil)

    def retranslateUi(self, pacceuil):
        _translate = QtCore.QCoreApplication.translate
        pacceuil.setWindowTitle(_translate("pacceuil", "Form"))
        self.label_25.setText(_translate("pacceuil", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Université </span><span style=\" font-size:24pt;\"><br/></span><span style=\" font-size:24pt; font-weight:600;\">Badji Mokhtar</span><span style=\" font-size:24pt;\"><br/></span><span style=\" font-size:24pt; font-weight:600;\">-Annaba-</span></p></body></html>"))
        self.plateforme_1.setText(_translate("pacceuil", "Plateforme"))
        self.listeEnseignants_1.setText(_translate("pacceuil", "Liste Enseignants"))
        self.documentation_1.setText(_translate("pacceuil", "Documentation"))
        self.departement_1.setText(_translate("pacceuil", "Département"))
        self.pushButton_11.setText(_translate("pacceuil", "Connexion"))
        self.label_27.setText(_translate("pacceuil", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#d5d5d5;\">Espace Enseignants :</span></p><p align=\"center\"><span style=\" font-size:36pt;\"><br/></span></p><p><span style=\" font-size:36pt;\"><br/></span></p></body></html>"))
        self.label_28.setText(_translate("pacceuil", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#d5d5d5;\">Identifiant</span><span style=\" font-size:24pt;\"><br/></span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.label_29.setText(_translate("pacceuil", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#d5d5d5;\">Mot de passe</span><span style=\" font-size:24pt;\"><br/></span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.pushButton_12.setText(_translate("pacceuil", "Connexion"))
        self.label_19.setText(_translate("enspage", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#d5d5d5;\">Thèmes :</span></p><p align=\"center\"><span style=\" font-size:36pt;\"><br/></span></p><p><span style=\" font-size:36pt;\"><br/></span></p></body></html>"))
        self.label_20.setText(_translate("enspage", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#d5d5d5;\">Ajouter un nouveau thème :</span></p><p align=\"center\"><span style=\" font-size:36pt;\"><br/></span></p><p><span style=\" font-size:36pt;\"><br/></span></p></body></html>"))
        self.label_21.setText(_translate("enspage", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#d5d5d5;\">Titre :</span><span style=\" font-size:24pt;\"><br/></span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.label_23.setText(_translate("enspage", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#d5d5d5;\">Niveau :</span><span style=\" font-size:24pt;\"><br/></span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.label_25.setText(_translate("enspage", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#d5d5d5;\">Description :</span><span style=\" font-size:24pt;\"><br/></span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.label_26.setText(_translate("enspage", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#d5d5d5;\">N° Thème :</span><span style=\" font-size:24pt;\"><br/></span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.ajouter.setText(_translate("enspage", "Ajouter"))
        self.label_30.setText(_translate("pacceuil", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#d5d5d5;\">Espace Etudiant :</span></p><p align=\"center\"><span style=\" font-size:36pt;\"><br/></span></p><p><span style=\" font-size:36pt;\"><br/></span></p></body></html>"))
        self.label_31.setText(_translate("pacceuil", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#d5d5d5;\">Identifiant</span><span style=\" font-size:24pt;\"><br/></span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.label_32.setText(_translate("pacceuil", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#d5d5d5;\">Mot de passe</span><span style=\" font-size:24pt;\"><br/></span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.label_34.setText(_translate("pacceuil", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Université </span><span style=\" font-size:18pt;\"><br/></span><span style=\" font-size:18pt; font-weight:600;\">Badji Mokhtar</span><span style=\" font-size:18pt;\"><br/></span><span style=\" font-size:18pt; font-weight:600;\">-Annaba-</span></p></body></html>"))
        self.label_35.setText(_translate("pacceuil", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Liens</span></p></body></html>"))
        self.label_36.setText(_translate("pacceuil", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Nous suivre</span></p></body></html>"))
        self.label_37.setText(_translate("pacceuil", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Nous contacter</span></p></body></html>"))
        self.label_40.setText(_translate("pacceuil", "<html><head/><body><p><span style=\" font-size:14pt;\">Adresse : Université Badji Mokhtar</span><br/><span style=\" font-size:14pt;\">-Annaba, B.P.12, Annaba 23000 Algérie</span></p></body></html>"))
        self.label_41.setText(_translate("pacceuil", "<html><head/><body><p><span style=\" font-size:14pt;\">Téléphone : +213 (0) 38 57 02 05</span></p></body></html>"))
        self.label_42.setText(_translate("pacceuil", "<html><head/><body><p><span style=\" font-size:14pt;\">E-mail : elearning@univ-annaba.dz</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pacceuil = QtWidgets.QWidget()
    ui = Ui_pacceuil()
    ui.setupUi(pacceuil)
    pacceuil.show()
    sys.exit(app.exec_())
